version: '3.4'

services:
  ms:
    image: ms
    build:
      context: node_modules/send/node_modules/ms
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
